import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import TurndownService from 'turndown';
import { bool, num, readCms, relations, text } from './lib/cms.mjs';
import { cleanHtml, ensureHtml } from './lib/html.mjs';
import { STATIC_IMAGES } from './lib/static-page-images.mjs';
import { ROOT, normalizeImageUrl } from './lib/webflow.mjs';

const DATA_DIR = path.join(ROOT, 'src', 'data');
const ARTICLES_DIR = path.join(ROOT, 'src', 'content', 'articles');
const MANIFEST = path.join(ROOT, 'scripts', 'image-manifest.json');
const PUBLIC_DIR = path.join(ROOT, 'public');

const BANNER = [
  '// Generated by scripts/import-cms.mjs from the Webflow CSV exports in cms/.',
  '// Do not hand-edit: run `npm run import:cms` instead.',
  '',
].join('\n');

const warnings = [];

function warn(message) {
  warnings.push(message);
}

const manifest = JSON.parse(await fs.readFile(MANIFEST, 'utf8'));

function resolveImage(rawUrl, alt, variant) {
  const url = normalizeImageUrl(rawUrl);
  if (!url) return undefined;
  const entry = manifest[url];
  if (!entry) {
    warn(`no manifest entry for ${url}`);
    return undefined;
  }
  const source = variant ? entry[variant] ?? entry : entry;
  return { src: source.src, width: source.width, height: source.height, alt: text(alt) };
}

function serialize(value) {
  return JSON.stringify(value, null, 2);
}

function bySourceOrder(a, b) {
  const left = new Date(text(a['Created On'])).getTime();
  const right = new Date(text(b['Created On'])).getTime();
  if (Number.isFinite(left) && Number.isFinite(right) && left !== right) return left - right;
  return text(a['Item ID']) < text(b['Item ID']) ? -1 : 1;
}

function toService(row) {
  const name = text(row.Name);
  const slug = text(row.Slug);
  const sections = [];
  for (const index of [1, 2, 3]) {
    const title = text(row[`Section ${index} Title`]);
    const html = cleanHtml(row[`Section ${index}`], { resolve: resolveImage, alt: title || name, warn });
    const image = resolveImage(row[`Section ${index} Image`], title || name);
    if (!title && !html && !image) continue;
    sections.push({ title, html, ...(image ? { image } : {}) });
  }
  return {
    name,
    slug,
    metaTitle: text(row['Meta Title']) || undefined,
    metaDescription: text(row['Meta Description']) || undefined,
    description: cleanHtml(row.Description, { resolve: resolveImage, alt: name, warn }),
    initialAppointment: bool(row['Initial Appointment']),
    visibleInNavigation: bool(row['Visible in Navigation']),
    visibleInServicesPage: bool(row['Visible in Services Page']),
    bookableInServicesPage: bool(row['Bookable in Services Page']),
    bookingText: cleanHtml(row['Booking Text'], { resolve: resolveImage, alt: name, warn }) || undefined,
    bookingLink: text(row['Booking Link']) || undefined,
    priority: num(row.Priority),
    priceRange: text(row['Price Range']) || undefined,
    icon: resolveImage(row.Image, name),
    heroImage: resolveImage(row['Hero Image'], name),
    sections,
    callToAction: ensureHtml(cleanHtml(row['Call To Action'], { resolve: resolveImage, alt: name, warn })) || undefined,
  };
}

function toDiscipline(row) {
  const name = text(row.Name);
  return {
    name,
    slug: text(row.Slug),
    metaTitle: text(row['Meta Title']) || undefined,
    metaDescription: text(row['Meta Description']) || undefined,
    description: cleanHtml(row.Description, { resolve: resolveImage, alt: name, warn }),
    icon: resolveImage(row.Icon, name),
    bookingLink: text(row['Booking Link']) || undefined,
    order: num(row.Order),
    visibleInNavigation: bool(row['Visible in Navigation']),
    heroImage: resolveImage(row['Hero Image'], name),
    pageContent: cleanHtml(row['Page Content'], { resolve: resolveImage, alt: name, warn }),
    practitioners: relations(row.Practictioners),
  };
}

function toPerson(row) {
  const name = text(row.Name);
  return {
    name,
    slug: text(row.Slug),
    title: text(row.Title),
    practitioner: bool(row.Practitioner),
    showInNavigation: bool(row['Show in Navigation']),
    summary: text(row.Summary) || undefined,
    description: cleanHtml(row.Description, { resolve: resolveImage, alt: name, warn }) || undefined,
    quote: text(row.Quote) || undefined,
    bookable: bool(row.Bookable),
    bookingText: cleanHtml(row['Booking Text'], { resolve: resolveImage, alt: name, warn }) || undefined,
    bookingLink: text(row['Booking Link']) || undefined,
    services: relations(row.Services),
    disciplines: relations(row.Disciplines),
    order: num(row.Order),
    mainImage: resolveImage(row['Main Image'], name),
    thumbnailImage: resolveImage(row['Thumbnail Image'], name),
    // fetch-images hangs the 160px crop off the thumbnail entry as a variant.
    avatar: resolveImage(row['Thumbnail Image'], name, 'avatar'),
  };
}

function servicesModule(services) {
  return `${BANNER}import type { Service } from '@/data/types';

export const SERVICES: Service[] = ${serialize(services)};

export const SERVICES_BY_PRIORITY: Service[] = [...SERVICES].sort((a, b) => a.priority - b.priority);

export const NAV_SERVICES: Service[] = SERVICES_BY_PRIORITY.filter((service) => service.visibleInNavigation);

export const INITIAL_SERVICES: Service[] = SERVICES_BY_PRIORITY.filter((service) => service.initialAppointment);

export const FOLLOW_UP_SERVICES: Service[] = SERVICES_BY_PRIORITY.filter((service) => !service.initialAppointment);

export function getService(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}
`;
}

function disciplinesModule(disciplines) {
  return `${BANNER}import type { Discipline } from '@/data/types';

export const DISCIPLINES: Discipline[] = ${serialize(disciplines)};

export const DISCIPLINES_BY_ORDER: Discipline[] = [...DISCIPLINES].sort((a, b) => a.order - b.order);

export const NAV_DISCIPLINES: Discipline[] = DISCIPLINES_BY_ORDER.filter(
  (discipline) => discipline.visibleInNavigation,
);

export function getDiscipline(slug: string): Discipline | undefined {
  return DISCIPLINES.find((discipline) => discipline.slug === slug);
}
`;
}

function peopleModule(people) {
  return `${BANNER}import type { Person } from '@/data/types';

export const PEOPLE: Person[] = ${serialize(people)};

export const PRACTITIONERS: Person[] = PEOPLE.filter((person) => person.practitioner).sort(
  (a, b) => a.order - b.order,
);

export const STAFF: Person[] = PEOPLE.filter((person) => !person.practitioner).sort(
  (a, b) => a.order - b.order,
);

export const FEATURED_PEOPLE: Person[] = PEOPLE.filter((person) => person.showInNavigation).sort(
  (a, b) => a.order - b.order,
);

export function getPerson(slug: string): Person | undefined {
  return PEOPLE.find((person) => person.slug === slug);
}
`;
}

function staticImagesModule() {
  const tree = {};
  for (const image of STATIC_IMAGES) {
    const asset = resolveImage(image.url, image.alt);
    if (!asset) {
      warn(`static image ${image.key} could not be resolved`);
      continue;
    }
    const segments = image.key.split('.');
    let node = tree;
    for (let index = 0; index < segments.length - 1; index += 1) {
      const next = segments[index + 1];
      const container = /^\d+$/.test(next) ? [] : {};
      node[segments[index]] = node[segments[index]] ?? container;
      node = node[segments[index]];
    }
    node[segments.at(-1)] = asset;
  }
  return `${BANNER}import type { ImageAsset } from '@/data/types';

export interface StaticImages {
  home: { hero: ImageAsset };
  services: { hero: ImageAsset; supplements: ImageAsset; herbalDispensary: ImageAsset };
  team: { hero: ImageAsset };
  articles: { hero: ImageAsset };
  contact: { hero: ImageAsset };
  ivTherapy: { hero: ImageAsset; sections: ImageAsset[] };
  partner: { logo: ImageAsset; photo: ImageAsset };
}

export const STATIC_IMAGES: StaticImages = ${serialize(tree)};
`;
}

const turndown = new TurndownService({
  headingStyle: 'atx',
  bulletListMarker: '-',
  codeBlockStyle: 'fenced',
  emDelimiter: '*',
});

turndown.addRule('rawFigure', {
  filter: ['figure'],
  replacement: (content, node) => `\n\n${node.outerHTML}\n\n`,
});

turndown.addRule('rawImage', {
  filter: ['img'],
  replacement: (content, node) => node.outerHTML,
});

turndown.addRule('externalLink', {
  filter: (node) => node.nodeName === 'A' && node.getAttribute('target') === '_blank',
  replacement: (content, node) => node.outerHTML,
});

turndown.keep(['table']);

function yamlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function yamlImage(asset) {
  return `{ src: ${yamlString(asset.src)}, width: ${asset.width}, height: ${asset.height}, alt: ${yamlString(asset.alt)} }`;
}

function isoDate(value) {
  const parsed = new Date(text(value));
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString();
}

async function writeIfChanged(file, contents) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  if (existsSync(file) && (await fs.readFile(file, 'utf8')) === contents) return false;
  await fs.writeFile(file, contents);
  return true;
}

async function main() {
  const cms = readCms();

  const services = [...cms.services.live].sort(bySourceOrder).map(toService);
  const disciplines = [...cms.disciplines.live].sort(bySourceOrder).map(toDiscipline);
  const people = [...cms.people.live].sort(bySourceOrder).map(toPerson);

  const serviceSlugs = new Set(services.map((service) => service.slug));
  const disciplineSlugs = new Set(disciplines.map((discipline) => discipline.slug));
  const peopleSlugs = new Set(people.map((person) => person.slug));

  for (const discipline of disciplines) {
    for (const slug of discipline.practitioners) {
      if (!peopleSlugs.has(slug)) warn(`discipline ${discipline.slug} references missing person ${slug}`);
    }
  }
  for (const person of people) {
    for (const slug of person.services) {
      if (!serviceSlugs.has(slug)) warn(`person ${person.slug} references missing service ${slug}`);
    }
    for (const slug of person.disciplines) {
      if (!disciplineSlugs.has(slug)) warn(`person ${person.slug} references missing discipline ${slug}`);
    }
  }

  await writeIfChanged(path.join(DATA_DIR, 'services.ts'), servicesModule(services));
  await writeIfChanged(path.join(DATA_DIR, 'disciplines.ts'), disciplinesModule(disciplines));
  await writeIfChanged(path.join(DATA_DIR, 'people.ts'), peopleModule(people));
  await writeIfChanged(path.join(DATA_DIR, 'static-images.ts'), staticImagesModule());

  await fs.mkdir(ARTICLES_DIR, { recursive: true });
  const expected = new Set();
  for (const row of cms.articles.live) {
    const slug = text(row.Slug);
    const title = text(row.Name);
    const author = text(row.Author);
    if (!peopleSlugs.has(author)) warn(`article ${slug} has author ${author || '(blank)'} who is not a live person`);
    const published = isoDate(row['Published On']) ?? isoDate(row['Created On']);
    if (!isoDate(row['Published On'])) warn(`article ${slug} has no Published On date`);
    const mainImage = resolveImage(row['Main Image'], title);
    const thumbnail = resolveImage(row['Thumbnail image'], title) ?? mainImage;

    const frontmatter = ['---', `title: ${yamlString(title)}`, `slug: ${yamlString(slug)}`];
    if (published) frontmatter.push(`publishedOn: ${yamlString(published)}`);
    frontmatter.push(`summary: ${yamlString(text(row['Post Summary']))}`);
    if (mainImage) frontmatter.push(`mainImage: ${yamlImage(mainImage)}`);
    if (thumbnail) frontmatter.push(`thumbnail: ${yamlImage(thumbnail)}`);
    frontmatter.push(`featured: ${bool(row['Featured?'])}`);
    frontmatter.push(`author: ${yamlString(author)}`);
    frontmatter.push('---');

    const html = cleanHtml(row['Post Body'], { resolve: resolveImage, alt: title, warn });
    const body = turndown.turndown(html).replace(/\n{3,}/g, '\n\n').trim();
    const file = path.join(ARTICLES_DIR, `${slug}.md`);
    expected.add(`${slug}.md`);
    await writeIfChanged(file, `${frontmatter.join('\n')}\n\n${body}\n`);
  }

  for (const file of await fs.readdir(ARTICLES_DIR)) {
    if (file.endsWith('.md') && !expected.has(file)) {
      await fs.rm(path.join(ARTICLES_DIR, file));
      warn(`removed stale article file ${file}`);
    }
  }

  const missing = new Set();
  for (const entry of Object.values(manifest)) {
    for (const asset of [entry, entry.avatar]) {
      if (asset && !existsSync(path.join(PUBLIC_DIR, asset.src.replace(/^\//, '')))) missing.add(asset.src);
    }
  }
  for (const src of missing) warn(`manifest points at missing file ${src}`);

  console.log(
    `cms: ${services.length} services, ${disciplines.length} disciplines, ${people.length} people, ` +
      `${cms.articles.live.length} articles`,
  );
  if (warnings.length > 0) {
    console.log(`notes (${warnings.length}):`);
    for (const message of [...new Set(warnings)]) console.log(`  ${message}`);
  }
}

await main();
