// Generated by scripts/import-cms.mjs from the Webflow CSV exports in cms/.
// Do not hand-edit: run `npm run import:cms` instead.
import type { ImageAsset } from '@/data/types';

export interface StaticImages {
  home: { hero: ImageAsset };
  services: { hero: ImageAsset; supplements: ImageAsset; herbalDispensary: ImageAsset };
  team: { hero: ImageAsset };
  articles: { hero: ImageAsset };
  contact: { hero: ImageAsset };
  ivTherapy: { hero: ImageAsset; sections: ImageAsset[] };
  partner: { logo: ImageAsset; photo: ImageAsset };
}

export const STATIC_IMAGES: StaticImages = {
  "home": {
    "hero": {
      "src": "/images/heroes/home.webp",
      "width": 1600,
      "height": 1068,
      "alt": "The Oak Clinic team gathered at the front reception desk"
    }
  },
  "services": {
    "hero": {
      "src": "/images/heroes/services.webp",
      "width": 1920,
      "height": 1080,
      "alt": "A patient booking an appointment on a tablet"
    },
    "supplements": {
      "src": "/images/pages/services-supplements.webp",
      "width": 1000,
      "height": 1500,
      "alt": "Shelves of professional supplements in the Oak Clinic dispensary"
    },
    "herbalDispensary": {
      "src": "/images/pages/services-herbal-dispensary.webp",
      "width": 1000,
      "height": 1500,
      "alt": "Dried herbs being measured into a bowl at the herbal dispensary"
    }
  },
  "team": {
    "hero": {
      "src": "/images/heroes/team.webp",
      "width": 1920,
      "height": 1080,
      "alt": "The Oak Clinic team at the front reception desk"
    }
  },
  "articles": {
    "hero": {
      "src": "/images/heroes/articles.webp",
      "width": 1920,
      "height": 1281,
      "alt": "A woman holding a head of freshly harvested lettuce"
    }
  },
  "contact": {
    "hero": {
      "src": "/images/heroes/contact.webp",
      "width": 1920,
      "height": 1080,
      "alt": "Oak Clinic reception desk beside the open sign"
    }
  },
  "ivTherapy": {
    "hero": {
      "src": "/images/heroes/iv-therapy.webp",
      "width": 1920,
      "height": 1080,
      "alt": "Patients relaxing in recliners during IV therapy"
    },
    "sections": [
      {
        "src": "/images/pages/iv-therapy-1.webp",
        "width": 1000,
        "height": 1500,
        "alt": "A practitioner adjusting an IV drip for a seated patient"
      },
      {
        "src": "/images/pages/iv-therapy-2.webp",
        "width": 1068,
        "height": 1600,
        "alt": "A practitioner hanging an IV bag on a stand"
      },
      {
        "src": "/images/pages/iv-therapy-3.webp",
        "width": 1000,
        "height": 1500,
        "alt": "Vials of vitamin B12 and B-complex injections on a tray"
      }
    ]
  },
  "partner": {
    "logo": {
      "src": "/images/pages/framework-nutrition-logo.webp",
      "width": 1000,
      "height": 200,
      "alt": "Framework Nutrition"
    },
    "photo": {
      "src": "/images/pages/framework-nutrition.webp",
      "width": 1000,
      "height": 1000,
      "alt": "Framework Nutrition meal plan cards showing recipes and nutrition facts"
    }
  }
};
